% read_pns_v2.m
%
%  Textread function for the PNS data file.  This file is for the PNS
%  format used in DVLNAV 172 to present.  A PNS string in this format has
%  130 whitespaces.
% For reading RAW DVLNAV files

function dop = read_pwhdop(filename)

fprintf(1,'Reading PWHDOP ascii data from from file %s \n', filename);
% [  dop.date(:,1)]   =   textread(filename,'%*3c %f/%*s %*s %*s');

[  dop.date(:,1),...
    dop.date(:,2),...
    dop.date(:,3),...
    dop.time(:,1),...
    dop.time(:,2),...
    dop.time(:,3),...
    dop.x,...
    dop.y,...
    dop.z]   =   textread(filename,'%*3c %f/%f/%f %f:%f:%f $PWHDOP,%f,%f,%f,%*s');
 
dop.t = ymdhms_to_sec(dop.date(:,1), dop.date(:,2), dop.date(:,3),...
        dop.time(:,1), dop.time(:,2), dop.time(:,3));
  
   
    
